### PR TITLE
ParsivelReader Functional Tests

### PR DESCRIPTION
**Pull request by josephhardinee**
This PR is a functional test for the ParsivelReader file type reader. It's fairly basic at the moment, but should provide a good base.

### CODE REVIEW

**Comment by josephhardinee** [comment]
@nguy If you get a chance, can you double check this works on your end. Either way I'll go through the other readers as I add their unit tests, but I wouldn't want to break the main merge branch if possible.

**Comment by nguy** [comment]
This seems to work for me just fine. 
As we discussed offline, we'll just have to rename the PIP files from NOAA aircraft examples.

**Comment by nguy** [comment]
Do you want me to go ahead an merge?

**Comment by josephhardinee** [comment]
Yes, but don't delete source branch.

**Comment by nguy** [comment]
okey dokey

**Pull request merged**
