### PR TITLE
Racoro reader

### PR DESCRIPTION
**Pull request by aamatthews**
Implemented a reader for the CAS 2ds combined files from the RACORO field campaign.

### CODE REVIEW

**Comment by josephhardinee** [comment]
This will be merged in shortly. We are just waiting on a few changes from another pull request before pulling this one in.

**Comment by josephhardinee** [comment]
Can you provide a shortened example file as well so I can add some unit tests to the reader?

**Comment by aamatthews** [comment]
Here is a sample file. CSV isn't supported for attaching here, but it is easy to copy this into Excel and create a CSV file of the data, which is what my reader works on.

[racoro_short_sample.txt](https://github.com/josephhardinee/PyDisdrometer/files/81628/racoro_short_sample.txt)

**Comment by josephhardinee** [comment]
This will need some rewriting to eliminate the preprocessing step, so I am closing this for now.

**Pull request closed without merging**
