### PR TITLE
Porting NOAA P-3 readers.

### PR DESCRIPTION
**Pull request by nguy**
Add 2D Image probe readers for specific NOAA P-3 processing.
Establised an 'io' folder for read routines.
Added io.common.py for commonly used routines.
Modified setup.py for installation.

I expect this to be an interative PR.

### CODE REVIEW

**Comment by nguy** [comment]
@josephhardinee I expect this to be iterative. The readers may be a not quite complete. Look at the dictionaries I used. If this is acceptable to use with all other readers we'll need to:
1. Modify the other readers to use dictionaries.
2. Modify DropSizeDistribution to accept dictionaries for calculations. I think this would be a very good enhancement.

**Comment by josephhardinee** [comment]
I am in favor of all of this. I'll start looking through everything this afternoon and can hopefully get a supporting change made soon for the dictionary changes.

**Comment by nguy** [comment]
I moved reader functions into the ```io``` directory and remapped the ```__init__.py``` accordingly. I began to modify ```ParsivelReader.py```, but realized I didn't know the file setup and thought you could do that quicker.

I also modified ```DropSizeDistribution``` to use dictionaries. I hope I caught all instances and thought this might save you time.

**Comment by josephhardinee** [comment]
I've looked through and I'm gonna make a few fixes to make documentation consistent. Do you have a test file for the new readers(The airplane data) I could test with? 

Also what do you think about changing calculated_fields back to fields? This should help to avoid breaking others code that depended on the field name.

**Comment by nguy** [comment]
Just shared 2 files with you.

I'm fine with the change. My thinking was that this way the user could track what was actually calculated by PyDisdrometer. Different instruments and organization provide some internal calculations that could conflict with this package unless they are named appropriately.

**Comment by nguy** [comment]
This is a big ask: Would you consider a package name change to PyDSD? Or even have the the install/import be ```pydsd```. This is largely driven by my laziness and inability to spell disdrometer correctly oftentimes.

**Comment by josephhardinee** [comment]
So I think the change to fields is fine, we can eventually add a computed field to it maybe to signify whether it was an intrinsic measurement or a computed field. Fields can also overlap somewhat as long as the access key is different(for instance have 'Zh' be scattered reflectivity while 'Z' is D**6 from the disdrometer). 
I would actually be okay with changing the package name as the goal is to support a lot of different type of DSD activity. I'll have to think about how that transition would go though. In the short term we could see if there is a way to have it import as pydsd as well.

**Comment by nguy** [comment]
In the case of these similar fields, we should take care that they are labelled the same across readers and calculations.

I just pushed some changes here that reorganize a bit more and allow ```import pydsd``` to work. It is a brute force fix for the moment, but we could massage this to be a bit cleaner if desired.

**Comment by nguy** [comment]
Let me know if you want me to change the ```calculated fields``` to ```fields``` or if you want to.

**Comment by josephhardinee** [comment]
All readers are supposed to return a dsd object, and it handles the computations so there shouldn't be too much of a risk of names being incorrect. The main risks are probably returned vs calculated velocity. We could probably rename the calculated. Or just use a standard set of names and put the onus on individual readers to know their input files better and handle it. It's probably easier to pick the standard set of names and handle the other cases as issues arrive. 

I'll go through this afternoon and probably just make the transition to pydsd be a proper one. There will be a little bit of recoding for users, but a single search and replace in their scripts will fix the issues. I'll also update to fields while at it.

**Comment by josephhardinee** [comment]
Actually I'll leave it as the dirty approach to the import for now. I want to think for a few days to see if I can make a list of other things this would effect(DSDs for instance) so we can fix all of those in one fell swoop.

**Comment by nguy** [comment]
Good idea. And feel free to accept or reject any changes I proposed there.
One thought is that we could switch the architecture to have all subfolders and function under the pydsd and then mirror the pydisdrometer for some time.

**Comment by josephhardinee** [comment]
I think this is encapsulated by all of the other PR's we've been doing? If so @nguy can you close this PR?

**Comment by nguy** [comment]
I believe you are right. Let's close this, we've made lot's of progress in the merge branch!

**Pull request closed without merging**
